AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    AutoPublishAlias: live
    Timeout: 10
  Api:
    BinaryMediaTypes:
      - image/webp
      - text/html
      - application/rss+xml

Resources:
  ImageProxy:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'image-proxy'
      Handler: proxy-image.handler
      MemorySize: 1024
      Runtime: nodejs18.x
      Environment:
      Policies:
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
      Layers:
        - arn:aws:lambda:us-east-1:342248164806:layer:lambda-layer-sharp:1
      Events:
        Create:
          Type: Api
          Properties:
            Path: /image/proxy
            Method: GET
  UrlProxy:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'url-proxy'
      Handler: proxy-url.handler
      MemorySize: 1024
      Runtime: nodejs18.x
      Environment:
      Policies:
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
      Layers:
        - arn:aws:lambda:us-east-1:342248164806:layer:lambda-layer-sharp:1
      Events:
        Create:
          Type: Api
          Properties:
            Path: /url/proxy
            Method: GET
